# Use a base image which provides as many of your dependencies as possible
FROM tutorial:votenet

# Add the files from your solution
ADD ./main/semantic_map_creation .
ADD ./main/guided_agent.py .
ADD ./main/votenet_benchbot.py .

# Make the command used to run your solution the default command
CMD ./semantic_map_creation
